root = "."

[build]
cmd = "go build -o ./tmp/main.exe ./cmd/api"
bin = "tmp/main.exe"
include_ext = ["go"]

[log]
main_only = false
time = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[screen]
clear_on_rebuild = false
keep_scroll = true
