### Health Check
GET http://localhost:4000/v1/healthcheck

### Get Single Movie
GET http://localhost:4000/v1/movies/10

### Create Movie
POST http://localhost:4000/v1/movies
Content-Type: application/json

{
  "title": "Interstellar",
  "year": 2014,
  "runtime": 169,
  "genres": [
    "Adventure",
    "Drama",
    "Sci-Fi"
  ],
  "director": "Christopher Nolan",
  "actors": [
    "Matthew McConaughey",
    "Anne Hathaway",
    "Jessica Chastain",
    "Michael Caine"
  ],
  "plot": "A team of explorers travels through a wormhole in space in an attempt to ensure humanity's survival.",
  "poster_url": "https://images-na.ssl-images-amazon.com/images/I/71v1icHXOWl._AC_SL1072_.jpg"
}

### Update Movie
PATCH http://localhost:4000/v1/movies/11
Content-Type: application/json

{
  "title": "Interstellars",
  "year": 2015,
  "runtime": 169,
  "genres": [
    "Adventure",
    "Drama",
    "Sci-Fi"
  ],
  "director": "Christopher Nolan",
  "actors": [
    "Matthew McConaughey",
    "Anne Hathaway",
    "Jessica Chastain",
    "Michael Caine"
  ],
  "plot": "A team of explorers travels through a wormhole in space in an attempt to ensure humanity's survival.",
  "poster_url": "https://images-na.ssl-images-amazon.com/images/I/71v1icHXOWl._AC_SL1072_.jpg"
}

### Delete Movie
DELETE http://localhost:4000/v1/movies/13